### PR TITLE
AMQPEnvelope instead of AMQPBasicProperties

### LINKED ISSUE #24: php-amqp 1.7.1
[php-amqp 1.7.1](https://github.com/pdezwart/php-amqp/tree/v1.7.1) doesn't have `AMQPBasicProperties` that is present only in `master` branch

### PR DESCRIPTION
**Pull request by thomasvargiu**
- Fix #24
- Allowed different service name for exchanges

### CODE REVIEW

**Comment by prolic** [comment]
There is a problem with this PR as it addresses too much things in a single PR, so I cannot cherry-pick - would have to take all or nothing.

I'm okay with some of those changes like:

`declare (strict_types=1);` to `declare(strict_types=1);`

Other things like the change of string concatination from:

`$this->logger->error('Exception: ' . $e->getMessage());` to `$this->logger->error('Exception: '.$e->getMessage());`

is something I really don't like.

Another thing that makes it more unreadable:

`if (! $this->lastDeliveryTag) {` to `if (!$this->lastDeliveryTag) {`

the space here really makes is more readable.

`@inheritdoc` to `{@inheritdoc}` is good on the other hand.

`@return integer` to `@return int` is also good and would be accepted.

The fix for #24 is rejected cause of reasons explained in the given issue. This library will be updated as soon as php-amqp launches a new release.

So really sorry, I have to reject this PR as is.

**Comment by thomasvargiu** [comment]
You're right, I'm sorry. I will submit another pull request, first for older amqp extension versions, and another one for binding names.

**Comment by prolic** [comment]
forget about older php-amqp versions! They only have problems!
1.8.0 is coming the next days, and this library will be upgraded then.

**Comment by thomasvargiu** [comment]
Ok! Thanky you!

**Comment by thomasvargiu** [comment]
@prolic just another thing.
In `.travis.yml` you have:
`- ./vendor/bin/php-cs-fixer fix -v --diff --dry-run`
so I applied these fix.

If you'll agree, I'll change it with `--level=psr2`.

**Comment by prolic** [comment]
no please not, I have this https://github.com/prolic/HumusAmqp/blob/master/.php_cs for php-cs rules - just updated a minute ago.

**Comment by thomasvargiu** [comment]
Much better! Thanks.

**Pull request closed without merging**
