### PR TITLE
Use pcntl_async_signals for php >=7.1

### PR DESCRIPTION
**Pull request by genhoi**
I suggest raising the minimum version of php to 7.1 and use pcntl_async_signals for best perfomance

### CODE REVIEW

**Comment by prolic** [comment]
Yes agree, I leave this ticket open for a short while, because this requires a minor version bump. I want to have all PR's merged before I put this in and tag a new release.

Thanks for your contribution.

**Comment by prolic** [comment]
Can you rebase this? Tests are failing.

**Comment by genhoi** [comment]
> Can you rebase this? Tests are failing.
I’ll do it tonight

**Comment by genhoi** [comment]
Done

**Pull request merged**
