### PR TITLE
Added a way to get default attributes.

### PR DESCRIPTION
**Pull request by bweston92**
Allow for:

```
$attributes = PlainProducer::defaultAttributes();
$attributes['request_id'] = $request->header('request_id');
new PlainProducer($attributes);
```

### CODE REVIEW

**Comment by prolic** [comment]
Sorry I don't get it...
1) What is it good for?
2) Why should it be public and static?

**Comment by bweston92** [comment]
So that I don't have to hard code the default attributes if I want to use the default plus 1 personal attribute.

```
$config = PlainProducer::defaultAttributes() + [
    'initial_request_id' => $request->header('request_id'),
];
```

vs

```
$config = [
    'content_type' => 'text/plain',
    'content_encoding' => 'UTF-8',
    'delivery_mode' => 2,
    'initial_request_id' => $request->header('request_id'),
];
```

**Comment by prolic** [comment]
`initial_request_id` is an invalid message attribute, you can add this to the headers like this:

    $config = [
        'content_type' => 'text/plain',
        'content_encoding' => 'UTF-8',
        'delivery_mode' => 2,
        'headers' => [
            'x-initial_request_id' => $request->header('request_id'),
        ]
    ];

But I get your point now. Let me think about it a while...

Thanks for the PR! :)

**Comment by bweston92** [comment]
Sorry I didn't know how the attributes are used (still need to read up on AMPQ) but yeah :)

**Comment by prolic** [comment]
@bweston92 Can you do the same for JsonProducer?

**Pull request merged**
